### ISSUE TITLE
Add another variant which uses an onboard temp sensor

### ISSUE THREAD

**Issue by askpatrickw** [askpatrickw/ESPHOME-BD35-Controller#2]
ChatGPT's opinons on how to do this... 

### Changes for Using Onboard Temperature Sensors Instead of Home Assistant Data

**1️⃣ Hardware Changes:**  
- Add two **wired temperature sensors**:  
  - **DS18B20** (digital, high accuracy) or  
  - **DHT22/BME280** (for ambient temp with humidity option).  

**2️⃣ Wiring Adjustments:**  
- Connect **DS18B20 sensors**:  
  - **Fridge Temp Sensor:** GPIO4 (OneWire Bus)  
  - **Ambient Temp Sensor:** GPIO16 (OneWire Bus)  
  - Add **4.7kΩ pull-up resistor** between **VCC and Data pin**.  

**3️⃣ ESPHome Config Changes:**  
- Replace **Home Assistant temp sensors** with **local sensors**:  

```yaml
# DS18B20 Temperature Sensors (Fridge & Ambient)
dallas:
  - pin: GPIO4  # Shared OneWire bus

sensor:
  - platform: dallas
    address: 0x3C0000031F0F1234  # Replace with actual address
    name: "Fridge Temperature"
    id: fridge_temp

  - platform: dallas
    address: 0x3C0000031F0F5678  # Replace with actual address
    name: "Ambient Temperature"
    id: ambient_temp
```

**4️⃣ Remove:**  
- **Home Assistant sensor integrations** (`sensor.fridge_temperature` & `sensor.outside_temperature`).  

**5️⃣ Keep Everything Else the Same.**  
- Adaptive cooling logic remains, now using onboard sensor data.  

---
### **✅ Summary of Changes**
✔ **Use DS18B20 sensors for onboard temperature readings.**  
✔ **Wire sensors to ESP32 and configure in ESPHome.**  
✔ **Remove dependency on Home Assistant temperature entities.**  
✔ **Keep all other features the same (PWM control, optocoupler, Turbo Mode, etc.).**  

Would you like a **wiring diagram** showing the sensor connections? 🚀
